services:
  - type: web
    name: peptide-ai-protocol-helper
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GEMINI_KEY
        value: AIzaSyA_bsRIVG9pwGes7fq2Tup9C20ybnEyRkM
      - key: NODE_ENV
        value: production
